#+TITLE: Dynamic Programming
#+AUTHOR: Prasanth Krishnan
#+EMAIL: knp281192@gmail.com
#+DESCRIPTION: This file contains my notes and coding samples for the topic Dynamic Programming.
#+OPTIONS: toc:2

* What is Dynamic Programming ?
Dynamic programming is a pradigm which gives us a way to create custom solutions to optimization problems. Optimization problem usually involve minimzing or maximizing a cost function. Algorithms for optimization problems require proof that they always return the best possible solution. Greedy algorithms that make the best local decisionat each step are typically efficient but usually do not guarantee global optimality. Exhaustive search algorithms like backtracking, that try all possibilities and select the best always produce the optimum result, but usually at a prohibitive cost in terms of time complexity.

Dynamic programming combines the best of both worlds. It gives us a way to design custom algorithms that systematically search all possibilities (thus guaranteeing correctness) while storing results to avoid recomputing (thus providing efficiency). By storing the consequences of all possible decisions and using this information in a systematic way, the total amount of work is minimized

DP is technique for efficiently implementing a recursive algorithm by storing the partial results and reusing them instead of computing them. Over used Example is Fibonacci numbers.


* When to use Dynamic Programming ?

* Steps to write a DP solution.

* Examples
